### PR TITLE
Create communities.json

### PR DESCRIPTION
**Pull request by Johanna-hub**
Added Code Your Future

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by Johanna-hub** [comment]
Do you mind if language specific?  In which case I could add - Django Girls, Pyladies, ClojureBridge, Node Girls, Rails Girls, R-Ladies, Women who Go

**Comment by eddiejaoude** [comment]
Sounds great! 👍 Thank you 🤓

**Comment by eddiejaoude** [comment]
Now next week, I will definitely need to consume the `json` with a small web application 😄

**Comment by Johanna-hub** [comment]
😀 will add those over weekend. Would be great if you could explain what you're going to do with it, (when you've got time)!

**Comment by eddiejaoude** [comment]
Great, no problem, when you get time 😄 .

My current thinking is to build a small web app to consume the `json` data and have a list with search and filter. I plan to look at it in more details the week after next. I will keep you posted on progress and will push my work up and we can chat / discuss 🤓 . Any questions / ideas etc just ask 😄

**Comment by eddiejaoude** [comment]
Good morning @Johanna-hub ,

Just to let you know, I modified the communities template for **social** information section, example below (also in `README.md`). Any questions let me know 😄 .

```json
{
  "name": "Name of Community",
  "description": "Description of the Community",
  "url": "https://github.com/WeRockTech/awesome-tech-communities",
  "logo": "https://raw.githubusercontent.com/WeRockTech/werocktech.github.io/master/img/twitter-banner.png",
  "social": [
    {
      "name": "twitter",
      "url": "http://twitter.com/CodeYourFuture_"
    }
  ],
  "codeOfConduct": false,
  "levels": ["beginner", "intermediate", "advanced"],
  "tags": ["Code", "Women", "Refugees", "TechForGood", "Inclusion", "Diversity"]
}
```

**Comment by Johanna-hub** [comment]
Looking forward to seeing you build the web app.  I feel a bit stuck in algorithms and tutorials, so will be great to see something being built!  Managed to sync my fork to master and make the changes!

**Comment by eddiejaoude** [comment]
Glad you managed to sync your fork with the upstream master 👍 . 

Yes algorithms and tutorials only go so far, its more fun to build a small application.

I am learning Angular4, so what I build was just following a tutorial - I am only 10% (2hours) of the way through the tutorial, so I am sure there are many improvements to be made 😄

**Comment by eddiejaoude** [comment]
@Johanna-hub  Steps I took so far to build the current application:

1. Installed & created a vanilla app using [Angular4 CLI](https://github.com/angular/angular-cli)
2. Added [Material Design](https://github.com/angular/material2) to the application (alternative to **bootstrap**) 
3. Used the **Angular4 CLI** to create a **component** called `communities`
4. In the new `communities` component 
   a. Create the **domain model** for a [community](https://github.com/WeRockTech/awesome-tech-communities/blob/angular/src/app/communities/community.ts) and [social](https://github.com/WeRockTech/awesome-tech-communities/blob/angular/src/app/communities/social.ts) - which creates the data structures
   b. Created a [service](https://github.com/WeRockTech/awesome-tech-communities/blob/angular/src/app/communities/community.service.ts) to read the `json` data 
   c. Updated the generated  [communities component](https://github.com/WeRockTech/awesome-tech-communities/blob/angular/src/app/communities/communities.component.ts) to use the **service** above and pass it to the view template
   d. Now the data is available to the [view](https://github.com/WeRockTech/awesome-tech-communities/blob/angular/src/app/communities/communities.component.html), used **material design** layout to make the data look presentable (still needs more work)

Hope that helps 😄

**Comment by Johanna-hub** [comment]
ah, amazing!  Thanks so much for this explanation.  Great to see the steps.

**Pull request merged**
